### ISSUE TITLE
Handle np.inf or -np.inf returned by objective_function/model

### ISSUE THREAD

**Issue by gr8den** [SimonBlanke/Hyperactive#10]
If _objective_function_ return _-np.inf_ some optimizers cannot handle it.

For example:

_EvolutionStrategyOptimizer_, _ParallelTemperingOptimizer_ throw exception
`AttributeError: 'NoneType' object has no attribute 'shape' `

_DecisionTreeOptimizer_ throw exception
`MemoryError: Unable to allocate 1.81 PiB for an array with shape (9857, 1620, 1620, 9857) and data type int64`

But _RandomSearchOptimizer_ works well

In my case objective function returns _-np.inf_ when no solution for selected set of parameters (e.g division by zero). Now function just returns big negative integer as workaround

**Comment by SimonBlanke** [comment]
Hello @gr8den 

thanks for opening this issue. This is a very important bug that you found there. 
Returning "-np.inf" or "np.inf" is important for many use cases, including early stopping.

I was able to reproduce the errors for _EvolutionStrategyOptimizer_ and _ParallelTemperingOptimizer_.
But for _DecisionTreeOptimizer_ i get:
```
.../python3.8/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

Could you provide the code that you ran for _DecisionTreeOptimizer_ ?

I will take a closer look at this in the optimization backend _Gradient-Free-Optimizers_.

**Comment by gr8den** [comment]
Hello @SimonBlanke

Yes, turns out changing -np.inf to -9999 not solve MemoryError for _DecisionTreeOptimizer_ (_BayesianOptimizer_,  _TreeStructuredParzenEstimators_)

Code for reproduce error:

```python
from hyperactive import Hyperactive
from hyperactive import DecisionTreeOptimizer, BayesianOptimizer, TreeStructuredParzenEstimators, RandomSearchOptimizer
import numpy as np

def fn(params):
  # return np.random.randn()
  return 123

search_space = {
  'a': np.arange(0, 9857),
  'b': np.arange(0, 1620),
  'c': np.arange(0, 1620),
  'd': np.arange(0, 9857),
}

# ok
# optimizer = RandomSearchOptimizer()

# MemoryError
# optimizer = BayesianOptimizer()
# optimizer = TreeStructuredParzenEstimators()
optimizer = DecisionTreeOptimizer()

hyper = Hyperactive(verbosity=False)
hyper.add_search(fn, search_space, optimizer=optimizer, n_iter=1000, memory=False)
hyper.run()
best_para = hyper.best_para(fn)

print(best_para)
```

Output:
```
MemoryError: Unable to allocate 1.81 PiB for an array with shape (1619, 9856, 1619, 9856) and data type int64
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-73-558e58d5309a> in <module>
     23 
     24 hyper = Hyperactive(verbosity=False)
---> 25 hyper.add_search(fn, search_space, optimizer=optimizer, n_iter=1000, memory=False)
     26 hyper.run()
     27 best_para = hyper.best_para(fn)
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/hyperactive/hyperactive.py in add_search(self, objective_function, search_space, n_iter, search_id, optimizer, n_jobs, initialize, max_score, random_state, memory, memory_warm_start)
     91             if optimizer == "default":
     92                 optimizer = RandomSearchOptimizer()
---> 93         optimizer.init(search_space, initialize)
     94 
     95         if search_id is not None:
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/hyperactive/optimizers.py in init(self, search_space, initialize)
     56         search_space_positions = self.trafo.search_space_positions
     57 
---> 58         self.optimizer = self._OptimizerClass(
     59             search_space_positions, initialize, **self.opt_params
     60         )
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gradient_free_optimizers/optimizers/sequence_model/decision_tree_optimizer.py in __init__(self, search_space, initialize, tree_regressor, xi, warm_start_smbo, rand_rest_p)
     30         rand_rest_p=0.03,
     31     ):
---> 32         super().__init__(search_space, initialize)
     33         self.tree_regressor = tree_regressor
     34         self.regr = tree_regressor_dict[tree_regressor]
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gradient_free_optimizers/optimizers/sequence_model/exp_imp_based_opt.py in __init__(self, search_space, initialize, xi, warm_start_smbo, rand_rest_p)
     31         rand_rest_p=0.03,
     32     ):
---> 33         super().__init__(search_space, initialize)
     34         self.new_positions = []
     35         self.xi = xi
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gradient_free_optimizers/optimizers/sequence_model/smbo.py in __init__(self, search_space, initialize, warm_start_smbo)
     25         self.Y_sample = []
     26 
---> 27         self.all_pos_comb = self._all_possible_pos()
     28 
     29     def init_warm_start_smbo(self):
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/gradient_free_optimizers/optimizers/sequence_model/smbo.py in _all_possible_pos(self)
     48 
     49         n_dim = len(pos_space)
---> 50         return np.array(np.meshgrid(*pos_space)).T.reshape(-1, n_dim)
     51 
     52     @track_X_sample
<__array_function__ internals> in meshgrid(*args, **kwargs)
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/numpy/lib/function_base.py in meshgrid(copy, sparse, indexing, *xi)
   4225 
   4226     if copy:
-> 4227         output = [x.copy() for x in output]
   4228 
   4229     return output
~/.pyenv/versions/3.8.6/lib/python3.8/site-packages/numpy/lib/function_base.py in <listcomp>(.0)
   4225 
   4226     if copy:
-> 4227         output = [x.copy() for x in output]
   4228 
   4229     return output
MemoryError: Unable to allocate 1.81 PiB for an array with shape (1619, 9856, 1619, 9856) and data type int64
```

**Comment by SimonBlanke** [comment]
Okay, I was able to reproduce both errors and I also found out the origin.

Both are located in the optimization backend: _Gradient-Free-Optimizers_

The error:
``` 
Unable to allocate 1.81 PiB for an array with shape (1619, 9856, 1619, 9856) and data type int64
```
is a behavior that is expected because of how sequence model based optimizers work:
In each iteration those optimizers calculate the approximate score in the search space of (in your case) size 1619* 9856* 1619* 9856. This means the algorithm has to do 1619* 9856* 1619* 9856 predictions. SBM-Optimizers are normally used for much smaller search spaces.

Maybe there are ways to use a sampling algorithm that returns a much smaller subset of those 1619* 9856* 1619* 9856 positions. This would probably make the smbo perform worse, but it would be able to run. I will open an issue in the _Gradient-Free-Optimizers_ repository about how to add this feature.

About the error:
``` 
AttributeError: 'NoneType' object has no attribute 'shape
```
This error occurs because the scores in the optimization backend are all set to "-np.inf"in the beginning. Those scores wait to be replaced by a better score during the run. A better score would update the best-score and best-position (which is None by default).
I will start working on a solution for this bug.

For now you could just use your workaround by returning "-9999".

**Comment by SimonBlanke** [comment]
All errors discussed in this issue have been fixed. These were:
 - AttributeError: 'NoneType' object has no attribute 'shape
 - ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Hyperactive and Gradient-Free-Optimizers can now handle np.nan and np.inf as a score from the objective function. Download the newest version of gradient-free-optimizers to fix the problem.
