### ISSUE TITLE
New feature: Save search-data during optimization run

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Hyperactive#13]
The user @DavidFricker asked for a way to save search-data during an ongoing optimization run in the issue SimonBlanke/Hyperactive#12. This is a feature i would like to implement as a helper-class in Hyperactive.

**Comment by SimonBlanke** [comment]
I am merging issue SimonBlanke/Hyperactive/#14 into this one. If a module for saving/reading search data to/from disk will be implemented i would like it to handle data types like python objects.

Do ensure data persistence of objects the "dill"-package could be used. To identify if objects are the same or not the user would have to manually name those objects.

**Comment by vanquanTRAN** [comment]
Thank you for your code sharing and your extraordinary development. I try to modify your code to show each iteration versus best score, that help us to show a graph n_iter vs best score. 
print('Iteration {}: Best Cost = {}'.format(best_iter, best_score=)). 
But i cant not succeed, 
Could you help me to handle this issue ? Thank you for your help.

**Comment by SimonBlanke** [comment]
Hello @vanquanTRAN,

thank you for requesting this feature, but as far as I understand the feature you request is **not** about "Save search-data during optimization run" but about displaying information about the optimization run. It would be better if you open a **new issue** and describe what you want to do (use the issue template).

**Comment by vanquanTRAN** [comment]
Thank you for your proposal

**Comment by SimonBlanke** [comment]
In https://github.com/SimonBlanke/Hyperactive/issues/13#issuecomment-788675719 I mentioned the possible usage of dill for python objects. From my most recent development I will not use dill to save objects from the search space. Instead it will be required to put objects into functions. This would look like in the code snippet from https://github.com/SimonBlanke/Hyperactive/issues/21#issue-833535514. This is a simpler solution with less dependencies.

**Comment by SimonBlanke** [comment]
The feature described in this issue is realized by the [simple-data-collector](https://github.com/SimonBlanke/simple-data-collector). I decided to outsource this feature into a separate repository, because it is a general problem/feature that can be useful independent of Hyperactive or optimization. It also helps to modularize the code and let the separate code packages interact with APIs.
