### ISSUE TITLE
Request TPE example

### ISSUE THREAD

**Issue by suciokhan** [SimonBlanke/Hyperactive#26]
Hello, the link you provide to TPE use example gives me a 404 error.
Here's the URL:
`https://simonblanke.github.io/Hyperactive/#/./optimizers/sequential_mehttps://github.com/SimonBlanke/Hyperactive/tree/master/examples/optimization_techniques/tpe.py`

**Comment by SimonBlanke** [comment]
Thank you @suciokhan! I just fixed the link for the example.
