### ISSUE TITLE
add multi gauss fit example

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Hyperactive#37]
An interesting example for gradient-free-optimization is fitting one or multiple gauss functions to data. The data can be generated with numpy for this example. 
A "real world" example of this problem is fitting gauss functions to particle-resonances in an energy spectrum. So this example should be very helpful for particle physicists.

**Comment by nevinadalal** [comment]
Hey, my team and I are interested in helping you out! Correct me if I am wrong, from our understanding you need a function whose input is a dataset and should return the parameters of the Gaussian curves that fit the data. Could you please shed more light on this?

> An interesting example for gradient-free-optimization is fitting one or multiple gauss functions to data. The data can be generated with numpy for this example. A "real world" example of this problem is fitting gauss functions to particle-resonances in an energy spectrum. So this example should be very helpful for particle physicists.

**Comment by SimonBlanke** [comment]
Hello @nevinadalal,

thanks for helping out! 

> from our understanding you need a function whose input is a dataset and should return the parameters of the Gaussian curves that fit the data

That is exactly it. The idea comes from a problem in physics:
You have an experiment in which you measured the energy spectrum of the decay products from some emitter (maybe a radioactive sample). The energy spectrum can be shown as a histogram similar to this: [researchgate link](https://www.researchgate.net/profile/D-Bazin/publication/224864655/figure/fig1/AS:393834384117760@1470908842154/Particle-identification-spectrum-The-three-oxygen-isotopes-22-O-23-O-and-24-O-were.png)
The type of particle can be identified by fitting gaussian functions to it. 

Since I have no experimental data we can instead create it ourself:
`
samples = np.random.normal(loc=2, scale=3, size=30000)
`
And later fit a gaussian function to those samples. (This would be a single gaussian fit)

If you are interested you can take [this example](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/master/examples/fit_gaussian.py) and develop upon it. You can add multiple peaks in the data (plus an offset of you like) and rewrite it as an hyperactive-example.

**Comment by nevinadalal** [comment]
Hi SimonBlanke
Sorry for the late reply, we have been pretty caught up with some finals.
We have made the function for fitting multiple gaussians and would be
sending you a pull request tonight. Just wanted to ask how would the
function be used in the package? Could you give an example of an
optimization algorithm where we could probably link it?

Hope to hear from you soon!

Regards
*Nevina Dalal*
Contact:
+919769422525
***@***.***

**Comment by Vanshikas253** [comment]
Hi SimonBlanke. This issue looked challenging and interesting, so me and my friends tried to solve it and came up with a solution. We were hoping to share our code with you. Can you please let us know your email ID so we can share it? Thanks!

**Comment by SimonBlanke** [comment]
Hello @Vanshikas253,

I am very interested in your solution! :-) if you open a pull-request we can take a look together.
