### ISSUE TITLE
AttributeError: module 'os' has no attribute 'mknod' within Progress Board

### ISSUE THREAD

**Issue by mlittmanabbvie** [SimonBlanke/Hyperactive#41]
**Look into the FAQ of the readme. Can the bug be resolved by one of those solutions?**
No 
**Describe the bug**
AttributeError: module 'os' has no attribute 'mknod'

**Code to reproduce the behavior**
```python
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.datasets import load_boston

from hyperactive import Hyperactive
from hyperactive.dashboards import ProgressBoard

data = load_boston()
X, y = data.data, data.target


def model(opt):
    gbr = GradientBoostingRegressor(
        n_estimators=opt["n_estimators"],
        max_depth=opt["max_depth"],
        min_samples_split=opt["min_samples_split"],
    )
    scores = cross_val_score(gbr, X, y, cv=3)

    return scores.mean()


search_space = {
    "n_estimators": list(range(50, 150, 5)),
    "max_depth": list(range(2, 12)),
    "min_samples_split": list(range(2, 22)),
}

progress_board = ProgressBoard()

hyper = Hyperactive()

hyper.add_search(
    model,
    search_space,
    n_iter=120,
    progress_board=progress_board,
)

hyper.run()
```

```Shell
**Error message from command line**
AttributeError                            Traceback (most recent call last)
<ipython-input-1-f7abb1559f49> in <module>
     34 
     35 # pass the instance of the ProgressBoard to .add_search(...)
---> 36 hyper.add_search(
     37     model,
     38     search_space,

~\Anaconda3\lib\site-packages\hyperactive\hyperactive.py in add_search(self, objective_function, search_space, n_iter, search_id, optimizer, n_jobs, initialize, max_score, early_stopping, random_state, memory, memory_warm_start, progress_board)
    142         optimizer = self._default_opt(optimizer)
    143         search_id = self._default_search_id(search_id, objective_function)
--> 144         progress_collector = self._init_progress_board(
    145             progress_board, search_id, search_space
    146         )

~\Anaconda3\lib\site-packages\hyperactive\hyperactive.py in _init_progress_board(self, progress_board, search_id, search_space)
    117     def _init_progress_board(self, progress_board, search_id, search_space):
    118         if progress_board:
--> 119             data_c = progress_board.init_paths(search_id, search_space)
    120 
    121             if progress_board.uuid not in self.progress_boards:

~\Anaconda3\lib\site-packages\hyperactive\dashboards\progress_board\progress_board.py in init_paths(self, search_id, search_space)
     38 
     39         self._io_.remove_progress(progress_id)
---> 40         self.create_lock(progress_id)
     41         data_c = DataCollector(self._io_.get_progress_data_path(progress_id))
     42         self.progress_collectors[progress_id] = data_c

~\Anaconda3\lib\site-packages\hyperactive\dashboards\progress_board\progress_board.py in create_lock(self, progress_id)
     26         path = self._io_.get_lock_file_path(progress_id)
     27         if not os.path.exists(path):
---> 28             os.mknod(path)
     29 
     30     def init_paths(self, search_id, search_space):

AttributeError: module 'os' has no attribute 'mknod'
```

**System information:**
OS Platform and Distribution
Windows 10
Python version 3.8.8
Hyperactive version 3.3.2

**Additional context**
From stackoverflow https://stackoverflow.com/questions/32691981/python-module-os-has-no-attribute-mknod
"os offers functionality that is closely related to the OS you're using. If most other attributes can be accessed from os (meaning you haven't got a os.py file in the current dir masking the standard module) an AttributeError will 99% signal an unsupported function on your Operating System.

This is what the case is with os.mknod on Windows. Creating named pipes in Windows has, as far as I can understand, very different semantics.

Either way, if you are trying to use mknod to create named pipes you'd probably be better using mkfifo() (again, only Unix supported) . If you're using it to create ordinary files, don't, use open() which is portable."

**Comment by SimonBlanke** [comment]
Thanks for reporting this issue.
This error occurs, because I am not developing or testing with the Windows OS in mind. Currently I do not have a Windows OS, but I will aim for testing in Windows in the future.

However I will close this issue, because the progress board in Hyperactive version 3.x was an experimental version with the streamlit library, which does not have good live update support. The problem with the live updates of the plots were discussed in SimonBlanke/Hyperactive#31. 
Therefore I will not develop this streamlit-based progress board any more. The future versions of Hyperactive will have access to a [panel](https://panel.holoviz.org/)-based dashboard for live plots. I already wrote a prototype, that seems to work reliably.
