### ISSUE TITLE
[MNT] transfer `setup.py` to `pyproject.toml`

### ISSUE THREAD

**Issue by fkiraly** [SimonBlanke/Hyperactive#73]
I would suggest to transfer `setup.py` to `pyproject.toml`.
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

**Comment by SimonBlanke** [comment]
The transfer of setup.py into pyproject.toml was done in [v4.8.0](https://github.com/SimonBlanke/Hyperactive/releases/tag/v4.8.0). I also changed the flat project layout into a src layout.
