### ISSUE TITLE
Out of memory when running Feature Selection (FS)

### ISSUE THREAD

**Issue by hanamthang** [SimonBlanke/Hyperactive#8]
Hi there, 

Thank you so much for your works on the Hyperactive library. Very useful to our works for Blue Carbon ecosystem evaluation. 

Could you have a look at the memory (RAM) consuming when running the Feature Selection? I executed your example for FS using my own data in Google Colab (12 Gb RAM) but always got out of memory. 

Anythings need to be noted here? 

Many thanks,
Thang

**Comment by SimonBlanke** [comment]
Hello @hanamthang,

i am happy to hear, that Hyperactive is useful to your work. Your use case sounds very interesting!

I ran the example, but could not see anything out of the ordinary. 
The dataset in the example is very small though. Could you tell me the size of your dataset (n rows, n columns)? I would then create a simulated dataset of that size and run the example again. Maybe i can recreate the out-of-memory error this way.

Until later,
Simon

**Comment by hanamthang** [comment]
Hi Simon,

Thank you for your reply. Yes, we intent to use the Hyperactive for machine learning models hyperparameters optimization and feature selection as well. :-) 

I ran your FS example without any problem, however stuck with the memory in Google Colab. My data is a small dataset, consisting of 85 rows and 29 columns (features). I used your example code with PSO for FS. 

Could you think of any potential problems here?

Thang

**Comment by SimonBlanke** [comment]
Hello Thang,

i was able to narrow down where the "out of memory"-error comes from. The initializer in the optimization backend "Gradient-Free-Optimizers" creates this error when searching in a high dimensional search space. 
I will open an issue in that repository.

However you can easily bypass this error by setting initialize={"random": 15}. 
This should not result in worse optimization results.

Anyway, i suggest you should use another optimizer for your type of problem. You have a lot of search dimensions that look like this: [True, False]. This won't give the particle swarm a lot of space to move.

The "EvolutionStrategyOptimizer" should be much better in this case. I suggest your optimization strategy should look like this:
```python
optimizer = EvolutionStrategyOptimizer(rand_rest_p=0.20)

hyper = Hyperactive()
hyper.add_search(
    model,
    search_space,
    n_iter=500,
    initialize={"random": 15},
    optimizer=optimizer,
)
hyper.run()
```

I hope i was able to help you with this.
Let me know if this solution works for you.

Simon

**Comment by hanamthang** [comment]
Hi Simon,

Thank you very much for your suggestions. I can run the Optimizer for FS without any memory errors appeared either using PSO or EvolutionStrategyOptimizer. The implementation of PSO is just to ensure that I can run your codes with my own data ;-). 

I'm happy that your package Hyperactive will support us a lot in the next research papers. 

Will you maintain this repository permanently? 

Thang

**Comment by SimonBlanke** [comment]
Hello Thang,

i am glad the optimization strategy works out for you now. It is also good to hear, that Hyperactive provides so much support for your research projects.
The Hyperactive project is very close to my heart, so i will maintain and upgrade it as long as possible.

Simon
