### ISSUE TITLE
[MNT] testing both `numpy` and `pandas` versions 1 and 2?

### ISSUE THREAD

**Issue by fkiraly** [SimonBlanke/Hyperactive#80]
Not necessarily a strong recommendation, but a question.

The python data/AI ecosystem is transitioning from `numpy` or `pandas` version 1 to version 2 only slowly, as dependencies add support with a delay, and deployed pipelines have a delay on top of that.

Would it be good to test, in a matrix, support for both versions 1 and 2? E.g., one "legacy" dependency set that has `numpy` and `pandas` latest 1.X version, and the "cutting edge" (or default) dependency set?

**Comment by SimonBlanke** [comment]
added testing-matrix for numpy and pandas in f05ad5e
