### ISSUE TITLE
[MNT] enable dependabot

### ISSUE THREAD

**Issue by fkiraly** [SimonBlanke/Hyperactive#81]
If not done, I would suggest to enable dependabot. This is integrated with GitHub, and can be done in the Settings.

There are version updates and security updates:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

This will automatically detect new version releases, and make PR with the updates, where tests run for inspection if anything breaks.

Currently there are no really strict upper bounds, but it would have spotted `pandas 2`, `numpy 2`, for instance.

**Comment by SimonBlanke** [comment]
Done in 05a813869df94fb1ff4a8397ac1e15896bb4dbfb
