### ISSUE TITLE
[BUG] `sklearn` `ObjectiveFunctionAdapter.objective_function` does not use `params`

### ISSUE THREAD

**Issue by fkiraly** [SimonBlanke/Hyperactive#96]
The `sklearn` `ObjectiveFunctionAdapter.objective_function` does not use the argument `params`, though perhaps it should?

Proposed fix: https://github.com/SimonBlanke/Hyperactive/pull/97

**Comment by SimonBlanke** [comment]
Wow, big oversight! Thanks for correcting this.
